version: '2.4'

services:
  app:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy

    volumes:
      - .:/srv
      - ./store:/store
    runtime: nvidia
    environment:
      - kaggle_username
      - kaggle_key
